services:
  wasm-app:
    build: .
    volumes:
      - .:/app  # This mounts the current directory to the container
      - ./docs:/app/docs  # Mount local build directory to /app/build
    ports:
      - "8080:8080"  # Expose the container's port to the host machine
    command: >
      sh -c "cp -r /built_files/* /app/docs/ && cd /built_files && cmake /app && make && python3 -m http.server 8080 --directory /app/docs"
    
